package-lock.json, package.json, screens/CreateProfileScreen.tsx, store/profile/profileActions.ts, store/profile/profileReducer.ts, store/profile/profileStates.ts
Set up the Profilereducer, profileaction and profilestate and imported the types, profilemocked data and did the setProfile function.
=> added profilereducer,action, state and the set profile function

screens/CreateProfileScreen.tsx
Har satt upp ska prifil sidan bara för en enkel mvp och för syns skull till att börja med
=> set up first createprofileaccount for the sight

screens/CreateTaskScreen.tsx, store/store.ts
- om man fyllt i titel och beskrivning så kan man skapa en task. 
-  just nu skapas alla tasks för household1 tills man kan få tag på statet vilket household som är aktivt tex.
- man kan skriva ut alla tasks genom att hämta taskSlice och skriva ut alla med taskSlice.tasks ....
=> 10 skapa sysslan med rätt information

App.tsx, contexts/themeContext.tsx, data/avatars.ts, data/theme.ts, screens/CreateProfileScreen.tsx
Added theme.ts
added themeContext.tsx
and set i up in App.tsx
added avatar.ts with enum avatar list ant the avatar colors
Now we can use the btton style in every screen and together fill the theme up
=> 20 add theme

data/index.ts, screens/CreateTaskScreen.tsx, store/tasks/taskSlice.ts, types.ts
- an editTask creator action in taskSlice
- example on how to use it:
```
const taskSlice = useAppSelector((state) => state.task); 
const testEditTask = (taskToEdit:Task) => {
const updatedTask = { ...taskToEdit, title: "MATA KATTEN" };
dispatch(editTask(updatedTask));
};
```
=> 12 redigera funktion i taskreducer

data/avatars.ts, screens/CreateTaskScreen.tsx
- laddat upp avatarer till imgur (koalan tex lite konstigt då jag tog bort bakgrundbilder från alla, men kan ju duga nu i början kanske)
- lagt  url i lista ihop med enum
- kommentar om hur användning kan se ut
=> 47 avatarer som url

App.tsx, data/theme.ts, modules/HouseholdMemberModal.tsx, screens/ProfileAccountScreen.tsx
- added the first view of the profileaccountscreen
-change the yellow color to more warm color in theme
. added a paperprovider in apptsx so we can use the modal
-setup a HouseHoldMemberModal to be shown when you click on modal
=> added the first setup of profileaccountscreen

navigators/RootNavigator.tsx, screens/HouseholdTasksScreen.tsx, screens/TaskDetailScreen.tsx, store/tasks/taskSlice.ts
1. The layout of task detail
2. link back to task list
3. effectFocus to rerender list when come back from task detail screen
4. change small detail css in task list
=> 46 task details layout

screens/ProfileAccountScreen.tsx
Removed statusbar from profileaccountscreen.
=> removed statusbar

README.md
Added grade-criteria for G and VG to readme.md
=> Added grade-criteria to the readme.md

screens/CreateUserAccountScreen.tsx
only added the theme from theme.ts
=> added theme to CreateUserAccount

screens/CreateProfileScreen.tsx, screens/ProfileAccountScreen.tsx, store/profile/profileSlice.ts
=> chnged the profileslice woth initialstate array

README.md, screens/ProfileAccountScreen.tsx, store/profile/profileSlice.ts
En Edit function i profileaccount, Nu kan man uppdatera namnet
=> Edit profileName

components/PiechartComponent.tsx, navigators/RootNavigator.tsx, navigators/TopTabNavigator.tsx, package-lock.json, package.json, screens/StatisticScreen.tsx
I have installed the necessary package react-native-pie-chart and have made a layout for the screen. I have a flatlist so the user can scroll all the different tasks the household has but I not quite sure if its the final layout. My thought is that we need to ask David how he wants the stat to be shown.
I have also experimented a little bit with dates and determine how to render this month, last month, this week and last week and will put a new issue for that.
The piechart for know is only temporary, just for shown. They will be altered later on.
=> 106 create piechart

navigators/RootNavigator.tsx
=> 109 custom header is back

api/config.ts, api/task.ts, store/tasks/taskSlice.ts
- now we config to the testbuzzter firestore but that can change in config.ts file
- i can add a task in task.ts under api by writing to the firestore db
=> 117 test fetching to firestore

README.md, screens/CreateTaskScreen.tsx, store/tasks/taskSlice.ts
- delete text is maybe out of place but the function is ready. we can delete a task.
=> 121 delete task

navigators/TopTabNavigator.tsx, screens/TESTDATUMSCREEN.tsx, utils/DateHandler.ts
Created DateHandler.ts in a utils-folder and a testscreen to print out the different dates.
=> Created DateHandler.ts and a testscreen to print out the different dates

README.md, screens/CreateProfileScreen.tsx, screens/HandleHouseholdScreen.tsx, screens/HouseholdAccountScreen.tsx, screens/ProfileAccountScreen.tsx, store/profile/profileSlice.ts
Man kan nu se tydligt vilka avtarer som är upptagna av andra medlemmar
=> 118 choose lediga avatarer

screens/StatisticScreen.tsx
I changed from flatlist to scrollview to be able to render the big piechart at the top and the other ones in a row.
=> Changed from flatlist to ScrollView on Statistisc.tsx layout

modules/HouseholdMemberModal.tsx, navigators/RootNavigator.tsx, screens/HandleHouseholdScreen.tsx, screens/HouseholdAccountScreen.tsx, screens/ProfileAccountScreen.tsx
Nu ser man alla profilers namn och avatar i "meddlemmar" modale i profilaccount
=> 133 update modal with active profiles

api/taskCompletion.ts, data/index.ts, screens/HouseholdTasksScreen.tsx, screens/ProfileAccountScreen.tsx, screens/TaskDetailScreen.tsx, store/taskCompletionSlice.ts, store/tasks/taskSlice.ts, types.ts
- la till householdid som egenskap på taskcompletion typen
- hämtar alla taskcompletions för ett hushåll när man går in på profilen för hushållet
=> 146 hämtar alla completions nu iallafall

App.tsx, contexts/themeContext.tsx, data/theme.ts, navigators/RootNavigator.tsx, screens/CreateUserAccountScreen.tsx, screens/HouseholdAccountScreen.tsx, screens/ProfileAccountScreen.tsx, screens/SignInScreen.tsx
Added lfirst setup ligt, darkmode, and changed som theme in screens
=> 140 lightdarkauto mode

api/profile.ts, screens/CreateProfileScreen.tsx, screens/HouseholdAccountScreen.tsx, screens/ProfileAccountScreen.tsx, store/profile/profileSlice.ts, store/store.ts
profilen hämtas från databasen när man går in på hushållet
dock funkar ej skapa korrekt då det måste skapas ett hushåll för det med
=> 151 crud profiles db 1

data/index.ts, screens/TESTDATUMSCREEN.tsx, utils/DateHandler.ts
Added a function to get todaysDate as format("yyyy-MM-dd")
=> Added some mocked data for taskCompletions as well

api/taskCompletion.ts
I added code for handling timestamp in taskCompletion.ts when adding taskCompletions to database and how to fetch data from current date to last months startdate.
Here I add the field timestamp to the taskCompletion without disturbing the type-structure:
Here I added dates and formated them to timestamp so we can do a query to fetch data from date 1 and date 2:
Further done in the same function I type up each data from the database as a TaskCompletion OMITE (without) the field completedTimestamp.
=> 166 change dates from string to timestamp

App.tsx, contexts/themeContext.tsx, data/theme.ts, navigators/RootNavigator.tsx, screens/HouseholdAccountScreen.tsx, screens/ProfileAccountScreen.tsx, screens/SignInScreen.tsx, screens/TESTDATUMSCREEN.tsx
light darkmode funkar på de sidor jag ser nu. och bakgrund på hushåll. 
Får småfixa när resten är uppe.
light ska vara ljusare
=> 157 fortsättning theme

api/task.ts, data/index.ts, modules/DeleteTaskModule.tsx, screens/CreateTaskScreen.tsx, store/tasks/taskSlice.ts, types.ts
OBS merga #172 PRen först :)
-ny egenskap i task är isActive
- nu kan man välja arkivera eller ta bort.
- vid arkivering sätts isActive=false
endast mvp modul, inte stylad än :)
=> 173 varning vid borttagning av syssla

components/ThemeSwitchButton.tsx, data/theme.ts, screens/CreateProfileScreen.tsx, screens/HandleHouseholdScreen.tsx, screens/HouseholdAccountScreen.tsx, screens/HouseholdTasksScreen.tsx, screens/SignInScreen.tsx
Ändrat gula och en del fix och mergat in tinas handle household. Börjar på ny branch och se romd et finns ngt som inte hängt emd här
=> 176 fortsättning theme

api/config.ts, api/profile.ts, api/task.ts, api/taskCompletion.ts, api/user.ts, package-lock.json, screens/CreateTaskScreen.tsx, store/tasks/taskSlice.ts
- add task och edit task THUNKS då det hanteras bättre vid async anrop
- extra reducers som bestämmer vad som händer med statet sen då när en task lagts till/redigerats
=> 188 error vid fetch anrop

api/household.ts, navigators/RootNavigator.tsx, screens/CreateTaskScreen.tsx, screens/HandleHouseholdScreen.tsx, screens/HouseholdTasksScreen.tsx, screens/ProfileAccountScreen.tsx, screens/TaskDetailScreen.tsx, store/household/householdSlice.ts
1. Created api calls inhousehold.ts
2. Removed header for HandleHousehold in rootNavigator
3. Changed HandleCreateHousehold
4. Added functions in householdSlice
A household is being added in database when clicking "Skapa", starting new issue for joining a household with the code
=> can create a household that is being added to the database

api/user.ts, data/index.ts, screens/CreateProfileScreen.tsx, screens/HandleHouseholdScreen.tsx, screens/HouseholdTasksScreen.tsx, screens/SignInScreen.tsx, store/household/householdSlice.ts
fixed so that the signin is from the database, will continue with my issue in another issue
=> fast fix for SigninScreen

api/household.ts, api/profile.ts, screens/HouseholdAccountScreen.tsx, store/household/householdSlice.ts
Get the profiles by userId,
gets the householdId from profiles,
get the households from the db.
In the HouseholdAccountScreen.tsx
=> 207 live coding fetch households from database

screens/HouseholdAccountScreen.tsx
Fixade handletoggle function och
set theme to button
=> 203 theme clean 1

api/profile.ts, screens/CreateProfileScreen.tsx, screens/CreateUserAccountScreen.tsx, screens/HandleHouseholdScreen.tsx, screens/HouseholdAccountScreen.tsx, screens/HouseholdTasksScreen.tsx, screens/ProfileAccountScreen.tsx, store/profile/profileSlice.ts, store/user/userSlice.ts
added profil to household when skapar ett hushåll
added saveupdatename to api and db
added householdcode
=> 214 get profile to profileaccount

api/household.ts, navigators/RootNavigator.tsx, screens/CreateProfileScreen.tsx, screens/HandleHouseholdScreen.tsx, screens/HouseholdAccountScreen.tsx, store/household/householdSlice.ts
Fixed joining households with Angelina
=> 209 continue with joining a household with code

api/household.ts, screens/ProfileAccountScreen.tsx, store/household/householdSlice.ts
set the edithouseholdname it works
=> 226 update householdname in profile

screens/CreateUserAccountScreen.tsx, screens/HandleHouseholdScreen.tsx, screens/SignInScreen.tsx
1. removed unnecessary code in CreateUserAccount
2. header in HandleHouseholdAccount now displayes the username and removed unnecessary code
3. changed color on statusbar in SigninScreen so the shade matches the rest of the application
=> fixed small issues

screens/StatisticScreen.tsx, types.ts, utils/statisticHandler.ts
Now the big piechart at the top is showing the total data for each profile. If theres no data, when loading or its empty is shows a gray piechart.
=> 234 big pie chart

screens/HouseholdAccountScreen.tsx
1. the theme button animation, swipping to left and right to change dark and light mode
=> swipe button works

App.tsx, README.md, api/config.ts, api/profile.ts, api/taskCompletion.ts, api/user.ts, navigators/RootNavigator.tsx, screens/CreateProfileScreen.tsx, screens/CreateUserAccountScreen.tsx, screens/HandleHouseholdScreen.tsx, screens/HouseholdAccountScreen.tsx, screens/ProfileAccountScreen.tsx, screens/SignInScreen.tsx, screens/TaskDetailScreen.tsx, store/household/householdSlice.ts, store/profile/profileSlice.ts, store/store.ts, store/taskCompletionSlice.ts, store/user/userAccountSlice.ts, store/user/userSlice.ts, types.ts
Now we log in with email and password. Had some trouble fetching households but now it works as intended again.
This merge will result in extra job for correcting some code...
=> 253 auth med firebase

navigators/RootNavigator.tsx
- state islogged in som blir false när man loggar ut i rootnavigation
=> state i rootnavigation som kollar om man är inloggad eller ej

api/profile.ts, navigators/RootNavigator.tsx, screens/CreateProfileScreen.tsx, screens/HandleHouseholdScreen.tsx, store/profile/profileSlice.ts
Nu när man skapar hushåll så kan man endast välja bee.
=> Pushar Angelinas kod här, man kan nu endast välja bee vid hushållsägare

navigators/TopTabNavigator.tsx
If theres no taskCompletions done for lastweek or lastmonth those screens doesnt show
=> Dont show stats-screens if theres no data

screens/CreateProfileScreen.tsx
Det blir grått när man valt en avatar, blir tydligt vilken an väljer
=> tydligt när en avatar är vald

README.md, api/config.ts, navigators/RootNavigator.tsx, package-lock.json, package.json, screens/HouseholdAccountScreen.tsx, store/user/userSlice.ts, tsconfig.json
Now you can login as a user and if you are not logged out  and you reload the app it will take you to HouseholdAccountScreen.tsx
=> 267 reset user stated when user is logging out

api/household.ts, components/HouseholdForm.tsx, screens/HandleHouseholdScreen.tsx, store/household/householdSlice.ts
thunk :) lite bättre tror jag nu!
=> 268 skapa hushåll segt

api/household.ts, screens/CreateProfileScreen.tsx, screens/HouseholdAccountScreen.tsx, screens/HouseholdTasksScreen.tsx, screens/SplashScreen.tsx, store/household/householdSlice.ts, store/profile/profileSlice.ts
Resolved some error-messages with thunks and changed lägg till-button to match Figma but I couldnt change the color of the text
=> 272 corrects bugs to householdaccountscreentsx

README.md, api/profile.ts, api/request.ts, api/task.ts, api/user.ts, navigators/RootNavigator.tsx, package-lock.json, package.json, screens/CreateProfileScreen.tsx, screens/HouseholdAccountScreen.tsx, screens/HouseholdTasksScreen.tsx, screens/SignInScreen.tsx, screens/TaskDetailScreen.tsx, store/household/householdSlice.ts, store/profile/profileSlice.ts, store/store.ts, store/taskCompletion/taskCompletionSlice.ts, store/tasks/taskSlice.ts, store/user/userSlice.ts, types.ts
- när man går med i hushåll skapas en förfrågan (HouseholdRequest)
- user har nu även email som egenskap (då den nu behövs)
- när man får till householdaccount så fetchas alla requests man har
- finns en funktion samt fetch för att acceptera en förfrågan men ej testad
- finns en request.ts fil under api
- finns en request mapp för en slice men den är tom
- thunks och cases för requests är i både householdslice och profileslice
=> 275 ägare får förfrågan vid ny profil

api/profile.ts, screens/ProfileAccountScreen.tsx, store/profile/profileSlice.ts
1. Added deactivateProfileInDB in Profile
2. Addede deactivateProfileAsync in ProfileSlice
3. Added HandleLeaveHouseholdClick in ProfileAccountScreen
Now when you choose to leave a household the isActive is set to false and navigates back to HouseholdAccount
=> Can now deactivate a profile when leaving the household

App.tsx, app.json, contexts/themeContext.tsx, data/theme.ts, screens/HouseholdAccountScreen.tsx, screens/ProfileAccountScreen.tsx
fixed the theme, and added a new button, 
set statusbar and auto in app.tsx
=> 270 theme auto 1

screens/CreateProfileScreen.tsx
=> nu är man ägare när man skapar hushåll igen

screens/CreateProfileScreen.tsx, screens/CreateTaskScreen.tsx, screens/HouseholdTasksScreen.tsx, store/tasks/taskSlice.ts
- when adding a task, dispatching of filtered task list happpends
- delete task is a thunk now
=> dispatchar filtrering av tasks vid adding a task. delete task thunk.

navigators/RootNavigator.tsx, screens/CreateUserAccountScreen.tsx, store/household/householdSlice.ts, store/profile/profileSlice.ts, store/taskCompletion/taskCompletionSlice.ts, store/tasks/taskSlice.ts, store/user/userSlice.ts
David helped with Auth(). Added .addCase that handles when a user is logged out.
When signing in as a new user you go directly to HouseholdAccountScreen.tsx
=> 295 onauth fixed

api/user.ts, modules/errorModule.tsx, screens/SignInScreen.tsx, store/user/userSlice.ts
- errorModule
- error state i userslice
- vid inlogg om misslyckat sätts state.error meddealnde
- errormodul kommer upp på signin vid error
=> 294 error meddelanden 1

navigators/TopTabNavigator.tsx, screens/HouseholdAccountScreen.tsx, screens/HouseholdTasksScreen.tsx, store/shared/CustomHeader.tsx
1. custom header title dynamicly changing
2. change the slice button to dropdown list for them mode
=> 262 customer header tittle

api/task.ts, api/taskCompletion.ts, navigators/RootNavigator.tsx, screens/CreateTaskScreen.tsx, store/taskCompletion/taskCompletionSlice.ts, store/tasks/taskSlice.ts, store/user/userSlice.ts
Error hantering vid
- hämtning av user (mappar om user)
- hämtning av tillagd taskcompletion (mappar om completion utan timestamp)
=> 301 error hantering i task och completions 1

screens/HouseholdAccountScreen.tsx
Added the logic to Tinas button in householdaccount
=> set the logic to the theme button

api/request.ts, data/theme.ts, modules/RequestModule.tsx, screens/HouseholdAccountScreen.tsx, screens/ProfileAccountScreen.tsx, store/request/requestSlice.ts
- i householdaccountscreen ser man om det finns förfrågan i hushållet
- i profileaccount screen syns en klocka längst ner om man är ägare och det finns förfrågningar
- det visas en lista på alla som förfrågat 
- man kan svara ja eller nej (ja - blir medlem. nej - profilen och requesten raderas)
Testa gärna efter buggar eller något knasigt
=> 313 ägare ska kunna svara på förfrågan att joina household

components/CreateHouseholdButton.tsx, components/Header.tsx, components/HouseholdItem.tsx, components/HouseholdList.tsx, components/LogoutButton.tsx, components/ModeThemeButton.tsx, screens/HouseholdAccountScreen.tsx
I fucked up BIG TIME! Second time TODAY I have commited to main! *hides face of embaressment*
So I did the simple thing and just copy-pasted all my code to a new branch.
=> 322 clean up householdaccountscreentsx

README.md, api/profile.ts, api/task.ts, modules/ChooseAvatarModule.tsx, modules/RequestModule.tsx, navigators/RootNavigator.tsx, screens/CreateTaskScreen.tsx, screens/ProfileAccountScreen.tsx, screens/TaskDetailScreen.tsx, store/tasks/taskSlice.ts, types.ts
- uppdaterade readme
- tog bort kommentarer från taskslice, task, createtaskscreen, rootnavigator någon, och någon mer kanske
=> 321 update readme and clean up in files with tasks

store/shared/CustomHeader.tsx, store/shared/CustomTabBar.tsx
change the go back icon location in householdTask screen
=> 307 changing go back icon in household task screen

components/HouseholdItem.tsx, components/HouseholdList.tsx
Fixed the issue with the missing key-props for each child in a list
=> Fixed the key-issue.

screens/CreateProfileScreen.tsx, screens/HandleHouseholdScreen.tsx, screens/ProfileAccountScreen.tsx
- ändrade från button till TouchableOpacity vid skapa hushåll och profil (för att få klick effekt)
- satte fast position på Gå ur hushåll knappen och klock-ikonen på profilsidan 
-pga de fick inte plats på telefonen att se beroende på hur de låg.
OBS testa branchsen innan den mergas på iphone helst så inte jag gjort helt kaos! :)
=> 326 bugfix profileaccount för stort samt knapp vid skapa hushåll 1

screens/CreateProfileScreen.tsx
1. create household does not need to choose avatar and it auto set to Bee
=> 334 fix the bee when creating household

screens/HandleHouseholdScreen.tsx
1. pop up warnings if a owner gå med his own hosehold
2. pop up error message if the join code is wrong
=> error handling with owner joining in house and wrong code

api/household.ts, screens/HandleHouseholdScreen.tsx, store/household/householdSlice.ts
1. modify the error message in handlehousehold screen
2. comment out the ****error logs **** in household slice **handleJoinHousehold function** and api household.ts  **checkHouseholdWithCode function**
=> change to using same error module and comment out the slice error log

screens/HouseholdTasksScreen.tsx
Now the button in HouseholdTaskScreen looks like the rest of them
=> Added theme to add-button

components/ModeThemeButton.tsx, contexts/themeContext.tsx
Chaned villkor i themecontext and got the changes to set rikgt theme.
=> 318 theme 20 2

package-lock.json, package.json, screens/HandleHouseholdScreen.tsx, screens/HouseholdTasksScreen.tsx, screens/SignInScreen.tsx, store/shared/CustomHeader.tsx
- annan key avoiding view i signin screen
- liiite större header för annars ser ej bee hiven ibland
men måste testas INNAN den tas in :)
=> 347 clean up and error handling vid behov

components/NewTaskButton.tsx, screens/HouseholdTasksScreen.tsx, store/shared/CustomHeader.tsx
added theme to custom and set a absolut look to Lägg till button so it shows for every mode
=> 319 bugg theme choises

components/ModeThemeButton.tsx
kolla denna på emulator android före merge
=> modebutton

api/household.ts, api/request.ts, components/CircleIntervalView.tsx, components/TaskCard.tsx, screens/CreateTaskScreen.tsx, store/tasks/taskSlice.ts
- ändrat lite färger i create task screen  med hjälp av Elina
- ändrat till svart ärg på text i householdtaskscreen
- gjort komponent av intervall med cirklarna i create task screeen
=> 366 komponentfix

api/household.ts, api/profile.ts, components/CircleIntervalView.tsx, components/TaskCard.tsx, screens/CreateTaskScreen.tsx, screens/HouseholdAccountScreen.tsx, screens/TaskDetailScreen.tsx, store/household/householdSlice.ts, store/profile/profileSlice.ts, store/user/userSlice.ts, tsconfig.json
- 31 nu som återkommande
- dock ej space between på värde
- david hjälpte oss med optimering vid hämtning av hushåll
=> 370 buggfix

components/ModeThemeButton.tsx, components/NewTaskButton.tsx, components/TaskCard.tsx, data/theme.ts, navigators/RootNavigator.tsx, screens/CreateUserAccountScreen.tsx, screens/HouseholdAccountScreen.tsx, screens/SignInScreen.tsx, screens/TaskDetailScreen.tsx
Some styling on headers and navigators. Removed where there shouldnt be any. Couldnt get my head around StatusBar. I installed a package but got errors from that so I removed it.
I may have changed things I shouldnt with this issue.... some buttons position and backgroundcolors.
=> 371 headers and navigators

components/TaskCard.tsx
I forgot a line with flexDirection: "row"
=> flexDirection for the avatars!

components/TaskCard.tsx
Deleted the mocked date.... this one is such a dumb thing to do! OF ME!
=> Deleted the mocked date

api/request.ts, api/user.ts, screens/CreateProfileScreen.tsx, screens/CreateTaskScreen.tsx, screens/CreateUserAccountScreen.tsx, screens/HouseholdAccountScreen.tsx, screens/ProfileAccountScreen.tsx, store/household/householdSlice.ts, store/profile/profileSlice.ts, store/shared/CustomHeader.tsx, store/shared/CustomTabBar.tsx, store/taskCompletion/taskCompletionSlice.ts, store/user/userSlice.ts
- error modul när man skapar konto
- focus effect i householdaccount screen (den andra i kommentar ifall man vill byta tillbaka)
- tog bort console logs
- satte error state i slices för att hantera error istället för att logga dom
- WIP med error hantering. även om error state sätts på många ställen så använder vi ju inte alltid dom än då.
=> 377 error handeling for when email allready exists

utils/statisticHandler.ts
Corrupt data in the database...
The profile I added doesnt exist.
Generated a errormessage that stopped the application. Sorted it with a if-statement.
=> Added a extra errorcheck for handling stats

README.md
Detta är Buzzter, hushållsappen till hela familjen. Skapa konto och bjud in hushållsmedlemmarna och dela på ansvaret på det gemensamma hemmet. Skapa sysslor och klara av dem. Statistik visar varje användares hårda slit och ger möjlighet till eftertanke och omtanke. Vi valde att använda oss av biet som är välkända för att arbeta i ett lag för ett gemensamt mål. Samt att vi vill lyfta biets nytta i världens alla hörn.
Buzzters utvecklades hösten 2023 av 5 ambitiösa studenter och vi använde oss av expo react native applikation tillsammans med esLint, github Action, prettier, Firestore för att nämna några.
För att komma igång med Buzzter behöver du vid nedladdning av denna kod köra `npm install`. För att köra programmet är det `npm start`som gäller i konsolen. Du kan använda din telefon eller …
=> Added text to readme.md

api/household.ts, api/profile.ts, api/request.ts, api/task.ts, api/user.ts, screens/CreateTaskScreen.tsx, screens/ProfileAccountScreen.tsx, screens/TaskDetailScreen.tsx, store/request/requestSlice.ts, store/taskCompletion/taskCompletionSlice.ts
- tog bort console errors 
- satte några state errors (detta är ju WIP) för fortsatt error-hantering
=> removed console error, set state error. removed else and comments
